# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine
WORKDIR /app

# install dependencies without running scripts
COPY package.json package-lock.json tsconfig.json ./
RUN npm install --ignore-scripts

# Copy source files
COPY src ./src

# Build the project
RUN npm run build

# Default command
CMD ["node", "dist/server.js"]
